# Generated by Django 4.2.5 on 2023-09-11 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=60, verbose_name='الاسم الاول')),
                ('lname', models.CharField(max_length=60, verbose_name='الاسم الثاني')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='المرتب')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True, verbose_name='خصومات')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='اسم المستخدم')),
            ],
            options={
                'verbose_name_plural': 'الموظف',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت الدخول')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الخروج')),
                ('benefits', models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=7, verbose_name='الربح')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مسئول الشيفت ')),
            ],
            options={
                'verbose_name_plural': 'الشيفت',
            },
        ),
        migrations.CreateModel(
            name='SalaryDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='المبلغ')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ الخصم')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='سبب الخصم')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SalaryDeduction', to='human_resources.workers', verbose_name='الموظف')),
            ],
            options={
                'verbose_name_plural': 'خصومات المرتب',
            },
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='وقت الدخول')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الخروج')),
                ('user_created_the_attendence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('worker_attended', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resources.workers', verbose_name='الموظف')),
            ],
            options={
                'verbose_name_plural': 'الحضور والانصراف',
            },
        ),
    ]
