# Generated by Django 4.2.5 on 2023-09-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_customer_alter_salarydeduction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name_plural': 'الشيفت'},
        ),
    ]
