# Generated by Django 4.2.5 on 2023-09-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_alter_shift_options'),
        ('human_resources', '0004_rename_worker_attended_attendence_employee_attended_and_more'),
    ]

    operations = [
    ]
