# Generated by Django 4.2.4 on 2023-09-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='الصنف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='السعر')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='الكميه')),
                ('available', models.BooleanField(default=True, verbose_name='متاح')),
                ('category', models.CharField(max_length=100, null=True, verbose_name='فئة')),
            ],
            options={
                'verbose_name_plural': 'المنيو',
            },
        ),
    ]
