# Generated by Django 4.2.5 on 2023-09-12 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0006_alter_shift_options'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الفئة')),
            ],
            options={
                'verbose_name_plural': 'الفئات',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت الاوردر')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='اجمالي السعر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resources.customer', verbose_name='العميل')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_set', to='human_resources.shift', verbose_name='شيفت')),
            ],
            options={
                'verbose_name_plural': 'الاوردرات',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='اسم الطاوله')),
            ],
            options={
                'verbose_name_plural': 'الطاولة',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='كميه')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='سعر')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.menu', verbose_name='الصنف')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='sales.order', verbose_name='اوردر')),
            ],
            options={
                'verbose_name_plural': 'عنصر الاوردر',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.table', verbose_name='طاولة'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.category', verbose_name='فئة'),
        ),
    ]
