# Generated by Django 4.2.4 on 2023-09-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_category_alter_menu_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='اسم الطاوله')),
            ],
            options={
                'verbose_name_plural': 'الطاولة',
            },
        ),
    ]
