<<<<<<< HEAD
# Generated by Django 4.2.4 on 2023-09-14 14:50
=======
# Generated by Django 4.2.5 on 2023-09-14 15:28
>>>>>>> aca2341c419eb04ba8572ba924a545a052d0aca7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0006_alter_shift_options'),
        ('sales', '0002_category_order_table_orderitem_order_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resources.customer', verbose_name='العميل'),
        ),
    ]
