# Generated by Django 4.2.4 on 2023-09-11 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت الاوردر')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='اجمالي السعر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('table_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.table', verbose_name='طاولة')),
            ],
            options={
                'verbose_name_plural': 'الاوردرات',
            },
        ),
    ]
