# Generated by Django 4.2.5 on 2023-09-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_order_options_alter_order_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=150, verbose_name='الصنف'),
        ),
    ]
