# Generated by Django 4.2.4 on 2023-09-12 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_customer_alter_salarydeduction_options_and_more'),
        ('sales', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resources.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_set', to='human_resources.shift', verbose_name='شيفت'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='كميه')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='سعر')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.menu', verbose_name='الصنف')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='sales.order', verbose_name='اوردر')),
            ],
            options={
                'verbose_name_plural': 'عنصر الاوردر',
            },
        ),
    ]
