# Generated by Django 4.2.5 on 2023-09-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_order_customer_order_shift_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='table_num',
            new_name='table',
        ),
    ]
