# Generated by Django 4.2.5 on 2023-09-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_active_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5, verbose_name='سعر'),
        ),
    ]
