# Generated by Django 4.2.5 on 2023-09-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_rename_customer_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_time'], 'verbose_name_plural': 'الاوردرات'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
