# Generated by Django 4.2.5 on 2023-09-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_orderitem_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='active_order',
        ),
    ]
