# Generated by Django 4.2.5 on 2023-09-12 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_alter_shift_options'),
        ('sales', '0007_alter_order_options_remove_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resources.customer'),
        ),
    ]
