<<<<<<< HEAD
# Generated by Django 4.2.4 on 2023-09-14 14:50
=======
# Generated by Django 4.2.5 on 2023-09-14 15:28
>>>>>>> aca2341c419eb04ba8572ba924a545a052d0aca7

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البدايه')),
                ('end_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ االانتهاء')),
                ('benefit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='الربح')),
                ('benefit_costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='مصاريف الفتره')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='صافي الربح')),
            ],
            options={
                'verbose_name_plural': 'الأرباح',
            },
        ),
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='وقت الدفع')),
                ('benefit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financials.benefits')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مسئول الشيفت')),
            ],
            options={
                'verbose_name_plural': 'المصاريف',
            },
        ),
    ]
