# Generated by Django 4.2.5 on 2023-09-16 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefits',
            options={'ordering': ['-id'], 'verbose_name_plural': 'الأرباح'},
        ),
        migrations.AlterModelOptions(
            name='costs',
            options={'ordering': ['-id'], 'verbose_name_plural': 'المصاريف'},
        ),
        migrations.AlterField(
            model_name='costs',
            name='benefit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financials.benefits'),
        ),
    ]
