# Generated by Django 4.2.5 on 2023-09-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_alter_benefits_options_alter_costs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='end_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ االانتهاء'),
        ),
    ]
