# Generated by Django 4.2.4 on 2023-09-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('admin', 'Admin'), ('superuser', 'SuperUser'), ('user', 'User')], default='user'),
        ),
    ]
